batch_size: 16
dataset_folder: data/MUTAG/
debug: false
device: cpu
early_stopping_epochs: 10
edge_feat_size: 6
gnn_layers: 2
hidden_size: 300
learning_rate: 0.01
max_epochs: 100
model: WLNClassifier
node_feat_size: 83
num_classes: 2
run_name: example
seed: 42
test_split: 0.1
train_split: 0.8
valid_split: 0.1
